# Generated by Django 4.1.2 on 2022-10-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
